version: '3'
services:
  web_ui:
    build:
      context: ./web_ui
    ports:
      - '7000:80'
    hostname: web_ui
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    volumes:
      - './data:/mnt/data'
    ports:
      - '7001:5000'
    hostname: backend
  training:
    build:
      context: ./
      dockerfile: ./training/Dockerfile
    volumes:
      - './data:/mnt/data'
    hostname: training
  wiki_extract:
    build:
      context: ./
      dockerfile: ./wiki_extract/Dockerfile
    volumes:
      - './data:/mnt/data'
    hostname: wiki_extract
