version: '3'
services:
  db:
    image: mysql:5.7.21
    restart: "no"
    volumes:
      - db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bda
      - MYSQL_USER=bda
      - MYSQL_PASSWORD=bda
    ports:
      - 127.0.0.1:3306:3306

volumes:
  db:
