version: '3'
services:
  web_ui:
    build:
      context: ./web_ui
    ports:
      - "7000:80"
    hostname: web_ui
  wiki_extract:
    build:
      context: ./
      dockerfile: ./wiki_extract/Dockerfile
    volumes:
      - "./wiki_dumps:/app/wiki_dumps"
    working_dir: /app
    command: bash run.sh
    hostname: wiki_extract
